### ISSUE TITLE
RPK calculation

### ISSUE THREAD

**Issue by nabilquraishi** [jiwoongbio/FMAP#7]
Hi,
Really like FMAP, starting to learn how to use it. Just wondered how you calculated RPK - I saw your code says readRpk = 1 / ($proteinLength * 3 / 1000). Wondered why you multiplied proteinlength by 3. Shouldnt it just be readRpk = 1 / ($proteinLength / 1000)?

Also would there be a update that builds a database on the entire Uniref90 for mapping and quantification rather than just the IDs that have KO. I would like to use it for gene enrichment analysis using GO.

Thanks,
Nabil

**Comment by jiwoongbio** [comment]
Hi Nabil,

The sequencing reads are nucleotide-level and the mapping database is
protein-level. To resolve the discordance between nucleotide-level and
protein-level, we multiply 3 on the protein length and obtain the CDS
length of nucleotide-level.

I am sorry to let you know that we have never planned to add a new function
of UniRef database only because one key feature of FMAP is providing a
protein database including orthology information.

Thanks,
Jiwoong

**Comment by nabilquraishi** [comment]
Ah of course that makes sense! Thanks Jiwoong.
