### ISSUE TITLE
Interpretation of FMAP pathway plot

### ISSUE THREAD

**Issue by ayan05** [jiwoongbio/FMAP#9]
Hi,
I am working on a dataset consisting of normal and crohn's disease patients sample.  After mapping KO genes to pathways I am getting a plot of pathways, but how to determine those differentially abundant pathways are from which sample?

**Comment by jiwoongbio** [comment]
Hi, I made a modification of FMAP_plot.pl code to show up/down proportions
as red/blue colors on the plot bars. Please try the new FMAP_plot.pl
Thanks for your feedback!

**Comment by ayan05** [comment]
Thank you!
Best,
Ayan

**Comment by sturne29** [comment]
Just to clarify: if you have a "control" and a "treatment" group, would the red indicate pathways that are more abundant in the treatment as compared to the control? I'm having a bit of trouble parsing the graph output.

**Comment by jiwoongbio** [comment]
@sturne29 Yes, you are right.

**Comment by TakacsBertalan** [comment]
Hi! I have a question about how to interpret the pathway plot. If I understand correctly, the bar is red if the indicated pathway is more abundant in my group than in the control, and blue if the pathway is more abundant in the control. My problem is that the plot created from my data shows multi-colored bars for several pathways and I am having a hard time interpreting this. Can it be a statistical error because of the small sample size (3 samples per group)?
[pathway_plot.pdf](https://github.com/jiwoongbio/FMAP/files/5776380/pathway_plot.pdf)

Thanks in advance!

EDIT: Okay, I think I got it. The bars show the whole pathway which consists of several genes. So it's possible for some members of the pathway to seem more abundant, while some are less abundant as in the control.
